# COMP9318 Lab4

## Instructions
1. This note book contains instructions for **COMP9318-lab4**.

* You are required to complete your implementation in a file `submission.py` provided along with this notebook.

* You are not allowed to print out unnecessary stuff. We will not consider any output printed out on the screen. All results should be returned in appropriate data structures via corresponding functions.

* You can submit your implementation for **lab4** via following link: http://kg.cse.unsw.edu.au:8318/lab4/ .

* For each question, we have provided you with detailed instructions along with question headings. In case of any problem, you can post your query @ Piazza.

* You are allowed to add other functions and/or import modules (you may have to in this lab), but you are not allowed to define global variables. **Only functions are allowed** in `submission.py`. 

* You should not import unnecessary modules/libraries, failing to import such modules at test time will lead to errors.

* We will provide immediate feedback on your submission. You can access your scores using the online submission portal on the same day. 

* For **Final Evaluation** we will be using a different dataset, so your final scores may vary.  

* You are allowed to submit as many times as you want before the deadline, but **ONLY the latest version will be kept and marked**.

* Submission deadline for this assignment is **23:59:59 on 22nd May, 2018**. We will **not** accept any late submissions.

# Question-1: Logistic Regression using Gradient Descent

* In this lab you are required to implement Logistic Regression using Gradient Descent.
* The training data is 2-dimensional data points from two classes namely: class-0, and class-1.

In [3]:
import pandas as pd
import numpy as np

data_file='./asset/a'
raw_data = pd.read_csv(data_file, sep=',')
raw_data.head()

Col1      Col2  Label
0  0.464726 -0.552165    0.0
1 -0.465277  0.155947    0.0
2 -0.367907  0.337509    0.0
3 -1.703355 -0.511965    0.0
4 -0.193367  0.642282    0.0

You need to **implement** logistic regression classifier (i.e., `logistic_regression()` in the file: `submission.py`). The input arguments of `logistic_regression()` are:
* `data`: Data in 2-columns format
* `labels`: Class-labels
* `coefficients`: Logistic Regression coefficients to be computed, initialized with $ZEROS$
* `num_epochs`: Number of epochs
* `learning_rate`: Learning rate of the algorithm 

The return value of `logistic_regression()` should be a numpy array containing the logistic regression **coefficients**. The coefficient corresponding to intercept term should be appended at the start of the array.

For example, a sample output is shown in the cell given below:

In [4]:
## Read in the Data...
data_file='./asset/a'
raw_data = pd.read_csv(data_file, sep=',')
labels=raw_data['Label'].values
data=np.stack((raw_data['Col1'].values,raw_data['Col2'].values), axis=-1)

## Fixed Parameters. Please do not change values of these parameters...
coefficients = np.zeros(3) # We initialize the coefficients with ZERO. We also compute the intercept term.
num_epochs = 20000
learning_rate = 50e-5

# data, labels, coefficients, num_epochs, learning_rate
data.shape, data.dtype, data.size, data.itemsize, data.ndim

((6000, 2), dtype('float64'), 12000, 8, 2)

In [4]:
X = data
y = labels

# features standerdization
# X_std = np.copy(X)

# X_std[:,0] = (X_std[:,0] - X_std[:,0].mean()) / X_std[:,0].std()
# X_std[:,1] = (X_std[:,1] - X_std[:,1].mean()) / X_std[:,1].std()

# Define Logistic Regression hypothesis or sigmoid function

def sigmoid(X, theta):
    
    z = np.dot(X, theta[1:]) + theta[0]
    
    return 1.0 / ( 1.0 + np.exp(-z))

# Define Logistic Regression Cost Function
def lrCostFunction(y, hx):
  
    # compute cost for given theta parameters
    j = -y.dot(np.log(hx)) - ((1 - y).dot(np.log(1-hx)))
    
    return j

# Gradient Descent function to minimize the Logistic Regression Cost Function.
def lrGradient(X, y, theta, alpha, num_iter):
    # empty list to store the value of the cost function over number of iterations
    cost = []
    
    for i in range(num_iter):
        # call sigmoid function 
        hx = sigmoid(X, theta)
        # calculate error
        error = hx - y
        # calculate gradient
        grad = X.T.dot(error)
        # update values in theta
        theta[0] = theta[0] - alpha * error.sum()
        theta[1:] = theta[1:] - alpha * grad
        
        cost.append(lrCostFunction(y, hx))
        
    return cost   

# m = Number of training examples
# n = number of features
m, n = X.shape

# set learning rate to 0.01 and number of iterations to 500
alpha = learning_rate
num_iter = 20000
theta = coefficients

print(alpha, num_iter)

# cost = lrGradient(X_std, y, theta, alpha, num_iter)
cost = lrGradient(X, y, theta, alpha, num_iter)

# print theta paramters 
print ('\n Logisitc Regression bias(intercept) term :', theta[0])
print ('\n Logisitc Regression estimated coefficients :', theta[1:])

0.0005 20000

 Logisitc Regression bias(intercept) term : -10.2034290687

 Logisitc Regression estimated coefficients : [-2.29067514  5.31366198]


In [6]:
def sigmoid(data, coefficients): 
    z = np.dot(data, coefficients[1:]) + coefficients[0]
    result = 1.0 / (1.0 + np.exp(-z))  
    return result

def logistic_regression(data, labels, coefficients, num_epochs, learning_rate):
    for i in range(num_epochs):
        hx = sigmoid(data, coefficients)
        error = hx - labels
        gradient = data.T.dot(error)
        coefficients[0] -= learning_rate * error.sum()
        coefficients[1:] -= learning_rate * gradient
        
    return coefficients

logistic_regression(data, labels, coefficients, num_epochs, learning_rate)

array([-10.20342907,  -2.29067514,   5.31366198])

In [1]:
import submission as submission
import numpy as np
import pandas as pd

## Read in the Data...
data_file='./asset/a'
raw_data = pd.read_csv(data_file, sep=',')
labels=raw_data['Label'].values
data=np.stack((raw_data['Col1'].values,raw_data['Col2'].values), axis=-1)

## Fixed Parameters. Please do not change values of these parameters...
coefficients = np.zeros(3) # We initialize the coefficients with ZERO. We also compute the intercept term.
num_epochs = 20000
learning_rate = 50e-5

coefficients=submission.logistic_regression(data, labels, coefficients, num_epochs, learning_rate)
print(coefficients)

[-10.20342907  -2.29067514   5.31366198]


In [2]:
import submission as submission

## Read in the Data...
data_file='./asset/a'
raw_data = pd.read_csv(data_file, sep=',')
labels=raw_data['Label'].values
data=np.stack((raw_data['Col1'].values,raw_data['Col2'].values), axis=-1)

## Fixed Parameters. Please do not change values of these parameters...
coefficients = np.zeros(3) # We initialize the coefficients with ZERO. We also compute the intercept term.
num_epochs = 20000
learning_rate = 50e-5

coefficients=submission.logistic_regression(data, labels, coefficients, num_epochs, learning_rate)
print(coefficients)

[-10.20342907  -2.29067514   5.31366198]


# Submission

You need to complete the function `logistic_regression()` in the file: `submission.py`. You can test your submission against sample test cases via online submission system (i.e., http://kg.cse.unsw.edu.au:8318/lab4/).


# Test Environment

For testing, we have pre-installed the requisite modules and/or libraries in the testing environment. You are only allowed to use following libraries:
* python: 3.5.2
* pandas: 0.19.2
* numpy: 1.14.0

NOTE: <br> 
* You are required to implement the gradint descent for logistic regression by yourself. You are not allowed to import **sklearn** and/or any other library in Lab4.
